#
# Copyright (c) 2019 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#
CONFIG_NCS_SAMPLES_DEFAULTS=y
CONFIG_DK_LIBRARY=y
CONFIG_CLOCK_CONTROL=y
#CONFIG_SYS_CLOCK_TICKS_PER_SEC=50000
CONFIG_NRFX_TIMER10=y
CONFIG_NRFX_DPPI10=y
CONFIG_NRFX_TIMER2=y
CONFIG_NRFX_TIMER3=y
